ユーザーモデルの作成
masatakamoroe/TodaysSchedule-API pull request #12
Opened 2020-10-12 02:39 UTC by masatakamoroe

ユーザーモデルの作成完了しました

2020-10-12 07:25 UTC, tsurutan requested changes
確認お願いします！

2020-10-12 07:25 UTC, tsurutan commented on app/views/devise/confirmations/new.html.erb
> +<h2>Resend confirmation instructions</h2>
[must]
rails APIで作成するため、viewまわりの処理は不要だと思います！
このファイルもそうですが、他にも作成している `views` 系は削除して良いと思います。

2020-10-12 07:25 UTC, tsurutan commented on config/routes.rb
> +  get 'pages/index'
[ask]
こちらの `pages` は何に使用しますでしょうか？

2020-10-12 07:53 UTC, masatakamoroe commented on config/routes.rb
> +  get 'pages/index'
[ask]
deviseの設定時にhttp://localhost:3000/にアクセスした際の最初のページを作成するために作りましたがRails APIで作成の場合は必要ないですよね。消します！

2020-10-12 08:08 UTC, masatakamoroe commented on app/views/devise/confirmations/new.html.erb
> +<h2>Resend confirmation instructions</h2>
[ask]
views系削除完了しました！
確認お願いいたします

2020-10-12 08:21 UTC, masatakamoroe commented on config/routes.rb
> +  get 'pages/index'
[ask]
pages削除しました。
ご確認宜しくお願いいたします。

2020-10-12 10:31 UTC, tsurutan requested changes
確認お願いします！

2020-10-12 10:31 UTC, tsurutan commented on app/views/devise/mailer/email_changed.html.erb
> +<p>Hello <%= @email %>!</p>
[must]
こｎプルリクで追加された `app/views` 配下のファイルは不要です！

2020-10-12 10:31 UTC, tsurutan commented on config/routes.rb
> +  get 'pages/index'
まだ消えていないです！
`get pages/index` も削除してください！
あと下の行のコメントアウトしているものも削除してください！

2020-10-12 10:31 UTC, tsurutan commented on app/helpers/pages_helper.rb
> +module PagesHelper
[must]
pagesも消すのでこのheplperも不要だと思います！

2020-10-12 10:31 UTC, tsurutan commented on app/controllers/pages_controller.rb
> +class PagesController < ApplicationController
[must]
pagesが不要なのでこのコントローラーも不要だと思います！

2020-10-12 10:31 UTC, tsurutan commented on app/assets/stylesheets/pages.scss
> +// Place all the styles related to the Pages controller here.
[must]
pagesが不要なので、このファイルも不要だと思います！

2020-10-12 14:43 UTC, masatakamoroe commented on config/routes.rb
> +  get 'pages/index'
削除しました

2020-10-13 03:15 UTC, tsurutan requested changes
1点確認お願いします！

2020-10-13 03:15 UTC, tsurutan commented on test/controllers/pages_controller_test.rb
> +require 'test_helper'
[must]
こちらも pages に関わるものなので不要だと思います！

2020-10-13 04:27 UTC, masatakamoroe commented on test/controllers/pages_controller_test.rb
> +require 'test_helper'
[ask]
削除いたしました！
確認宜しくお願い致します。

2020-10-13 04:42 UTC, tsurutan approved these changes
LGTM!!

2020-10-13 04:46 UTC, merged