devise token auth完了
masatakamoroe/TodaysSchedule-API pull request #13
Opened 2020-10-24 07:59 UTC by masatakamoroe

devise token　完了しました！
ご確認宜しくお願い致します。

2020-10-25 03:26 UTC, tsurutan requested changes
確認お願いします！

2020-10-25 03:26 UTC, tsurutan commented on 
> +
[must]
このファイルは不要だと思います！

2020-10-25 03:26 UTC, tsurutan commented on app/models/user.rb
> +            # Include default devise modules.
[must]
インデントは揃えましょう！

2020-10-25 03:26 UTC, tsurutan commented on config/routes.rb
> +      resources :users, only: :index
[ask]
こちらのコードはどうして書かれていますでしょうか？

2020-10-25 03:26 UTC, tsurutan commented on db/migrate/20201024060941_add_columns_to_users.rb
> +  end
[must]
このファイルの中身はすべてコメントアウトされているため、実際このファイルは何もしません。
ので削除しましょう！

2020-10-25 07:11 UTC, masatakamoroe commented on app/models/user.rb
> +            # Include default devise modules.
揃えました！

2020-10-25 07:11 UTC, masatakamoroe commented on db/migrate/20201024060941_add_columns_to_users.rb
> +  end
削除しました！

2020-10-25 07:12 UTC, masatakamoroe commented on config/routes.rb
> +      resources :users, only: :index
前回のバグでnamespaceが必要だったので追加しましたが、
必要なさそなので削除します！

2020-10-25 09:42 UTC, tsurutan commented on db/migrate/20201024060941_add_columns_to_users.rb
> +  end
このファイル自体以来ないので削除しましょう！

2020-10-26 00:31 UTC, tsurutan approved these changes
LGTM!

2020-10-26 00:44 UTC, merged