Calendarモデル作成
masatakamoroe/TodaysSchedule-API pull request #18
Opened 2020-10-29 06:49 UTC by masatakamoroe

モデル作成
カラム追加

2020-10-29 08:20 UTC, masatakamoroe reviewed
WIP
コード確認宜しくお願い致します

2020-10-29 08:20 UTC, masatakamoroe commented on db/migrate/20201029063108_create_calendars.rb
> +class CreateCalendars < ActiveRecord::Migration[6.0]
WIP
コード確認宜しくお願い致します

2020-10-29 14:52 UTC, tsurutan requested changes
念のため `rails console` で `Calendar` インスタンス の作成、 `Calendar` インスタンスから `user` インスタンスを一つ参照できることの確認をしてください。

2020-10-29 14:52 UTC, tsurutan commented on db/migrate/20201029063108_create_calendars.rb
> +      t.datetime :date
[ask]
dateはnullであってもよいのでしょうか？

2020-10-29 14:52 UTC, tsurutan commented on db/migrate/20201029063108_create_calendars.rb
> +      t.string :id
[must]
railsでは `create_table` をするとデフォルトで `id` が作成されるためこちらの記述は不要です。
```
By default, create_table will create a primary key called id
```
https://guides.rubyonrails.org/active_record_migrations.html#creating-a-table

2020-10-29 14:52 UTC, tsurutan commented on db/migrate/20201029063108_create_calendars.rb
> +      t.string :title
[ask]
titleはnullでも大丈夫でしょうか？

2020-10-30 04:55 UTC, masatakamoroe commented on db/migrate/20201029063108_create_calendars.rb
> +      t.string :id
削除しました

2020-10-30 04:57 UTC, masatakamoroe commented on db/migrate/20201029063108_create_calendars.rb
> +      t.string :title
titleとdatetimeに　, null: falseを追加しました

2020-10-30 04:57 UTC, masatakamoroe commented on db/migrate/20201029063108_create_calendars.rb
> +      t.datetime :date
, null: falseを追加しました

2020-10-30 05:22 UTC, masatakamoroe commented on db/migrate/20201029063108_create_calendars.rb
> +      t.string :id
[ask]
create_table :calendars do |t|を
削除しrails db:migrateを行った際にtメソッドのNameErrorが出ました
undefined local variable or method `t' for #<CreateCalendars:0x00007fa5a6d23108>
create_table :calendars, id: false do |t|を行うべきでしょうか？

2020-10-30 09:13 UTC, tsurutan commented on app/models/calendar.rb
> +
[must]
migrationファイルに null falseを書きましたが、これはあくまでデーターベース上での成約であり、 rails アプリケーションでの成約ではありません。
rails アプリケーションでも、値に成約を加えるため `validation` を記入しましょう。
https://railsguides.jp/active_record_validations.html

2020-10-31 07:21 UTC, tsurutan commented on app/models/calendar.rb
> +  validates :title, length: { maximum: 20 }
[imo]
validates :title, length: { maximum: 20 }, presence: true

とバリデーションする対象はまとめたほうが良いと思います。

2020-10-31 07:21 UTC, tsurutan commented on test/fixtures/calendars.yml
> +  holiday_id: 1
[imo]
こちらは不要だと思うので消しましょう。

2020-11-01 04:13 UTC, masatakamoroe reviewed
[ask]
> 念のため `rails console` で `Calendar` インスタンス の作成、 `Calendar` インスタンスから `user` インスタンスを一つ参照できることの確認をしてください。

参照方法はこれであっていますか？
#<Calendar id: nil, title: nil, date: nil, user_id: nil, created_at: nil, updated_at: nil>

2020-11-01 04:13 UTC, masatakamoroe commented on db/migrate/20201029063108_create_calendars.rb
> +      t.datetime :created_at, null: false
[ask]
rails db:migrateをしたら
エラーが出ました
こちらもt.datetime :created_at
     　　　 t.datetime :updated_at
 t.timestampsがあるので必要ないということでしょうか？
you can't define an already defined column 'created_at'.
/Users/masatakamoroe/src2/TodaysSchedule-API/db/migrate/20201029063108_create_calendars.rb:10:in `block in change'
/Users/masatakamoroe/src2/TodaysSchedule-API/db/migrate/20201029063108_create_calendars.rb:3:in `change'

2020-11-01 04:13 UTC, masatakamoroe commented on app/models/calendar.rb
> +
記入しました

2020-11-01 04:13 UTC, masatakamoroe commented on app/models/calendar.rb
> +  validates :title, length: { maximum: 20 }
まとめました

2020-11-01 04:13 UTC, masatakamoroe commented on test/fixtures/calendars.yml
> +  holiday_id: 1
消しました！

2020-11-03 01:11 UTC, tsurutan requested changes

2020-11-03 01:11 UTC, tsurutan commented on db/migrate/20201024022336_devise_token_auth_create_users.rb
> +      t.integer :uid, :null => false, :default => ""
[must]
`uid` は railsでデフォルトで作成される `id` とは異なるため、こちらは `string` のままで大丈夫です。

2020-11-03 01:11 UTC, tsurutan commented on app/models/calendar.rb
> +  belongs_to :user, optional: true
[must]
`optional: true` を設定すると、User を指定しなくても Rails アプリケーションは許可してしまうので、こちらの設定は消しましょう。

2020-11-03 01:43 UTC, tsurutan approved these changes
LGTM!

2020-11-13 13:48 UTC, tsurutan requested changes
確認お願いします。

2020-11-13 13:48 UTC, tsurutan commented on Gemfile
> +gem 'grape'
こちらにdevise grape token などのgemが書かれていませんが大丈夫でしょうか？###

2020-11-13 13:48 UTC, tsurutan commented on app/api/api.rb
> +  GrapeDeviseTokenAuth.setup! do |config|
こちらは　config/initializer/grape_devise_auth.rb に書きましょう。

2020-11-13 13:48 UTC, tsurutan commented on app/api/entities/v1/root_entity.rb
> +module Entities
こちらは不要です。

2020-11-13 13:48 UTC, tsurutan commented on app/api/resources/v1/calendar.rb
> +          @calendars = ::Calendar.all
：：は不要です。

2020-11-13 13:48 UTC, tsurutan commented on app/api/resources/v1/calendar.rb
> +          @calendars = ::Calendar.all
いまの書き方だとユーザーにかかわりなくすべてのカレンダーを取得できてしまいます。
特定のユーザーのカレンダーのみ取得できるようにしましょう。

2020-11-13 13:48 UTC, tsurutan commented on app/api/resources/v1/calendar.rb
> +
この改行は不要です。

2020-11-13 13:48 UTC, tsurutan commented on app/api/resources/v1/calendar.rb
> +        desc 'calendar'
このAPIはまだ不要です。
削除してください。

2020-11-13 13:48 UTC, tsurutan commented on config/application.rb
> +    #config.autoload_paths += Dir[Rails.root.join('app', 'api', '*')]
これらコメントは不要です。削除してください。

2020-11-13 13:48 UTC, tsurutan commented on config/routes.rb
> +    mount API => '/'
namespace で api などのprefixをつけるのではなく grape の機能を使って付けましょう。
この API を namespace の中から外してください。

2020-11-16 10:33 UTC, tsurutan requested changes
確認おねがいします。

2020-11-16 10:33 UTC, tsurutan commented on app/api/api.rb
> +  mount Resources::V1::Root
これはclass内に書きましょう。

2020-11-16 10:33 UTC, tsurutan commented on app/api/entities/v1/calendar_entity.rb
> +      expose :id, :title, :date, :user_id
user_idまで公開する必要はないと思います。

2020-11-16 10:33 UTC, tsurutan commented on app/api/entities/v1/root_entity.rb
> +module V1
このファイルは不要だと思います。

2020-11-16 10:33 UTC, tsurutan commented on app/api/resources/v1/calendar.rb
> +          @calendars = Calendar.all
この書き方だとユーザーかかわりなくこのままだとすべてのカレンダーが返ってしまいます。
まずどのようにして、authenticate_user!後にユーザーを参照できるか考えてみましょう。

2020-11-23 08:36 UTC, tsurutan requested changes

2020-11-23 08:36 UTC, tsurutan commented on app/api/resources/v1/calendar.rb
> +     resource :calendars do
インデントがずれています。

2020-11-23 08:36 UTC, tsurutan commented on config/initializers/grape_devise_auth.rb
> +  end
インデントがずれています。

2020-11-23 08:36 UTC, tsurutan commented on config/routes.rb
> +    mount_devise_token_auth_for 'User', at: '/auth'
インデントがずれています。

2020-11-23 08:36 UTC, tsurutan commented on db/seeds.rb
> +Calendar.create(title: 'Sonytitel', date:'2020.0101', user_id: '1')
user_id は数字です。文字になってます。

2020-11-23 09:37 UTC, tsurutan approved these changes
一点コメントしました。
こちらを修正したらLGTMです。

2020-11-23 09:37 UTC, tsurutan commented on app/controllers/application_controller.rb
> +      end
こちらインデントがずれています。

2020-11-23 09:51 UTC, merged