POSTメソッド作成
masatakamoroe/TodaysSchedule-API pull request #20
Opened 2020-11-25 08:09 UTC by masatakamoroe

条件
・HTTP METHOD はPOST
・endpointは api/v1/calendars
・ヘッダーに認証情報を持たせる
・パラメータにカレンダー情報を持たせる
・ヘッダーでユーザー特定、パラメータをもとにカレンダー作成
・正しくないパラメータを送ってきた場合はエラーメッセージを返す

ご確認宜しくお願い致します。

2020-11-25 13:25 UTC, tsurutan requested changes
確認お願いいたします！

2020-11-25 13:25 UTC, tsurutan commented on app/api/resources/v1/calendars.rb
> +            user_id: params[:user_id],
[must]
このようにパラメーターでユーザーのid を指定してしまうと、自分ではないユーザーのカレンダーも作成できてしまいます。これを防ぐにはどのようにすれば良いでしょうか？

2020-11-25 14:20 UTC, masatakamoroe commented on app/api/resources/v1/calendars.rb
> +            user_id: params[:user_id],
current_user.idにしました。

2020-11-26 01:39 UTC, tsurutan commented on app/api/resources/v1/calendars.rb
> +            user_id: params[:user_id] = current_user.id,
こちらの params[:user_id] はどのような役割になるのでしょうか？

2020-11-26 04:11 UTC, masatakamoroe commented on app/api/resources/v1/calendars.rb
> +            user_id: params[:user_id] = current_user.id,
params[:user_id]を削除し
createメソッドを変更しました。

2020-11-26 13:43 UTC, tsurutan approved these changes
LGTM!!

2020-11-26 16:13 UTC, merged